language: java
sudo: false
dist: trusty
cache:
  directories:
    - $HOME/.m2
jdk:
- oraclejdk8
install: true
script: ./travis/build.sh
notifications:
  irc: # "irc.rizon.net#runelite"
  #    - secure: "Zs0qWTwP3ug3dos7P10fSIhNyvDgatviCbcbsXVJnMDI18LIQC7VqIIp4Le0FdrFLtQ7yg9UTpa+mraFzoD5JZrQ86YRi0LHCJYzPIxh8gZIHpCKC1K1Iq4AZGUcDHYqQp19xOFuPjsfrZe/HRSF/3Zvyk7GsLSWmzIdOZQ/ydXUzttENsdl5mqO9Ys3ibPg9zZ6xlZvxgz7QGgPRKwlEudsmNYnOGr8L3XPaR/jF7IqeNCoKGS3kh2LQ53JWs5eVP2ej8bhq2Cy6X7DBKT1VudZ1vfAqfwB57jMbAGSMhcYKTi+0ESCiGJZ5qxz21Ie23Y96LX0cH7zDFyOYvIGVNxS5xwINJbXb4t7V72nP4cHUpjlnPz9yLuLRouOi3CHbiEkeuiQrpS6JmHHQKvd0K7GznxKfxrrW1b/c9CItIXi7VbaLAX9sjNtq5mggE0oyyv6bNqpf/VF1gMsA0AvIU12CkSDkZTmWlg4xcRy/l4CWLNjSPNUMU/TSS1OEz64pcG4qmrsxLQsnjXNzo+nIEmmjPiBsqNctL7u4Whc5xZak7mbxqEqfY87VqcZICGjpAW8CHFuU5yQhTjyg8rY/IdrSkHinVJZTFXla6mW9aLbMrt4ZT90opXX2S9tb1SouuCRj2qqjU3tKx5KH6Z/O0hbnyyyqehOnNxfWNGVEKM="
    channels:
      - secure: "kCIbETLib1Og7LLD7hM+GLVg/BYk/hhKt/MhABUxB09TLDmqCkK/JvWcf5It6y4HCzxLP4fZ29Bt8E6XU7PYEkCwJOUlbpG+7AS3F0MZ+WFFH6+CttZ+01PQkSJdAUshy3lGPQHhpzPgxjzazRZ33qPXqyEXkfTHgWzhYhsM91frR0w7Vev8pat9EmqL7jnFv7xZYlPphP5mZRLeV810eRrk/2O9bKTU2iMEPSa3fRXko8Fma7BLPuhDZxdsG9gBhRw7Bh/+7mPxDCMPd9DJfLhGijCIQkBRpmABRrDevbdU8LqSC94e2IOC3Ul9J+E7B/zZppEpDKF1lg0EboZCZW+7CMNx8T3z88k/VOEXVCZHvBmON/PUReWHdeicevq43z6V7PxqvjZmmp1e41NqRUFmB+5odgEA0vxoIrwIOOofu3lxd+x48N/7BeeN28TLsomLHYIj0v+VczSIPuxJ4JUb2fehfnmMnJjSM1G/jU5TySzbjVMvnBM3HmWQoADvdDu7PTKhM8pCDGbV8+Lbuxt19GTLLYaOGQriSTNv6G9nx0u7VatS1KWhVXpD4hqwPZEs6enWkFW3RoLWTBAbc137Kt3FfmP4gL0KMYO5x0eElswxVo2ZVikGP2xzSfzPkg8ReeRJWjDwLqfium4VytWwtsvPNYwCSGqxFbmV3zU="
