// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: party.proto

package net.runelite.client.party;

public final class Party {
  private Party() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface JoinOrBuilder extends
      // @@protoc_insertion_point(interface_extends:party.Join)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>int64 partyId = 1;</code>
     * @return The partyId.
     */
    long getPartyId();

    /**
     * <code>int64 memberId = 2;</code>
     * @return The memberId.
     */
    long getMemberId();
  }
  /**
   * <pre>
   * c-&gt;s
   * </pre>
   *
   * Protobuf type {@code party.Join}
   */
  public  static final class Join extends
      com.google.protobuf.GeneratedMessageLite<
          Join, Join.Builder> implements
      // @@protoc_insertion_point(message_implements:party.Join)
      JoinOrBuilder {
    private Join() {
    }
    public static final int PARTYID_FIELD_NUMBER = 1;
    private long partyId_;
    /**
     * <code>int64 partyId = 1;</code>
     * @return The partyId.
     */
    @java.lang.Override
    public long getPartyId() {
      return partyId_;
    }
    /**
     * <code>int64 partyId = 1;</code>
     * @param value The partyId to set.
     */
    private void setPartyId(long value) {
      
      partyId_ = value;
    }
    /**
     * <code>int64 partyId = 1;</code>
     */
    private void clearPartyId() {
      
      partyId_ = 0L;
    }

    public static final int MEMBERID_FIELD_NUMBER = 2;
    private long memberId_;
    /**
     * <code>int64 memberId = 2;</code>
     * @return The memberId.
     */
    @java.lang.Override
    public long getMemberId() {
      return memberId_;
    }
    /**
     * <code>int64 memberId = 2;</code>
     * @param value The memberId to set.
     */
    private void setMemberId(long value) {
      
      memberId_ = value;
    }
    /**
     * <code>int64 memberId = 2;</code>
     */
    private void clearMemberId() {
      
      memberId_ = 0L;
    }

    public static Party.Join parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Party.Join parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Party.Join parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Party.Join parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Party.Join parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Party.Join parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Party.Join parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Party.Join parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Party.Join parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static Party.Join parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Party.Join parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Party.Join parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(Party.Join prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * c-&gt;s
     * </pre>
     *
     * Protobuf type {@code party.Join}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          Party.Join, Builder> implements
        // @@protoc_insertion_point(builder_implements:party.Join)
        Party.JoinOrBuilder {
      // Construct using net.runelite.client.party.Party.Join.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>int64 partyId = 1;</code>
       * @return The partyId.
       */
      @java.lang.Override
      public long getPartyId() {
        return instance.getPartyId();
      }
      /**
       * <code>int64 partyId = 1;</code>
       * @param value The partyId to set.
       * @return This builder for chaining.
       */
      public Builder setPartyId(long value) {
        copyOnWrite();
        instance.setPartyId(value);
        return this;
      }
      /**
       * <code>int64 partyId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPartyId() {
        copyOnWrite();
        instance.clearPartyId();
        return this;
      }

      /**
       * <code>int64 memberId = 2;</code>
       * @return The memberId.
       */
      @java.lang.Override
      public long getMemberId() {
        return instance.getMemberId();
      }
      /**
       * <code>int64 memberId = 2;</code>
       * @param value The memberId to set.
       * @return This builder for chaining.
       */
      public Builder setMemberId(long value) {
        copyOnWrite();
        instance.setMemberId(value);
        return this;
      }
      /**
       * <code>int64 memberId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMemberId() {
        copyOnWrite();
        instance.clearMemberId();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:party.Join)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new Party.Join();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "partyId_",
              "memberId_",
            };
            java.lang.String info =
                "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0002\u0002\u0002" +
                "";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<Party.Join> parser = PARSER;
          if (parser == null) {
            synchronized (Party.Join.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<Party.Join>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:party.Join)
    private static final Party.Join DEFAULT_INSTANCE;
    static {
      Join defaultInstance = new Join();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        Join.class, defaultInstance);
    }

    public static Party.Join getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Join> PARSER;

    public static com.google.protobuf.Parser<Join> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface PartOrBuilder extends
      // @@protoc_insertion_point(interface_extends:party.Part)
      com.google.protobuf.MessageLiteOrBuilder {
  }
  /**
   * Protobuf type {@code party.Part}
   */
  public  static final class Part extends
      com.google.protobuf.GeneratedMessageLite<
          Part, Part.Builder> implements
      // @@protoc_insertion_point(message_implements:party.Part)
      PartOrBuilder {
    private Part() {
    }
    public static Party.Part parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Party.Part parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Party.Part parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Party.Part parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Party.Part parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Party.Part parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Party.Part parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Party.Part parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Party.Part parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static Party.Part parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Party.Part parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Party.Part parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(Party.Part prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code party.Part}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          Party.Part, Builder> implements
        // @@protoc_insertion_point(builder_implements:party.Part)
        Party.PartOrBuilder {
      // Construct using net.runelite.client.party.Party.Part.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      // @@protoc_insertion_point(builder_scope:party.Part)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new Party.Part();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = null;java.lang.String info =
                "\u0000\u0000";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<Party.Part> parser = PARSER;
          if (parser == null) {
            synchronized (Party.Part.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<Party.Part>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:party.Part)
    private static final Party.Part DEFAULT_INSTANCE;
    static {
      Part defaultInstance = new Part();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        Part.class, defaultInstance);
    }

    public static Party.Part getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Part> PARSER;

    public static com.google.protobuf.Parser<Part> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface DataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:party.Data)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>bytes data = 1;</code>
     * @return The data.
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code party.Data}
   */
  public  static final class Data extends
      com.google.protobuf.GeneratedMessageLite<
          Data, Data.Builder> implements
      // @@protoc_insertion_point(message_implements:party.Data)
      DataOrBuilder {
    private Data() {
      data_ = com.google.protobuf.ByteString.EMPTY;
    }
    public static final int DATA_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>bytes data = 1;</code>
     * @return The data.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getData() {
      return data_;
    }
    /**
     * <code>bytes data = 1;</code>
     * @param value The data to set.
     */
    private void setData(com.google.protobuf.ByteString value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      data_ = value;
    }
    /**
     * <code>bytes data = 1;</code>
     */
    private void clearData() {
      
      data_ = getDefaultInstance().getData();
    }

    public static Party.Data parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Party.Data parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Party.Data parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Party.Data parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Party.Data parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Party.Data parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Party.Data parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Party.Data parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Party.Data parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static Party.Data parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Party.Data parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Party.Data parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(Party.Data prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code party.Data}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          Party.Data, Builder> implements
        // @@protoc_insertion_point(builder_implements:party.Data)
        Party.DataOrBuilder {
      // Construct using net.runelite.client.party.Party.Data.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>bytes data = 1;</code>
       * @return The data.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getData() {
        return instance.getData();
      }
      /**
       * <code>bytes data = 1;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setData(value);
        return this;
      }
      /**
       * <code>bytes data = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        copyOnWrite();
        instance.clearData();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:party.Data)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new Party.Data();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "data_",
            };
            java.lang.String info =
                "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\n";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<Party.Data> parser = PARSER;
          if (parser == null) {
            synchronized (Party.Data.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<Party.Data>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:party.Data)
    private static final Party.Data DEFAULT_INSTANCE;
    static {
      Data defaultInstance = new Data();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        Data.class, defaultInstance);
    }

    public static Party.Data getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Data> PARSER;

    public static com.google.protobuf.Parser<Data> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface C2SOrBuilder extends
      // @@protoc_insertion_point(interface_extends:party.C2S)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>.party.Join join = 1;</code>
     * @return Whether the join field is set.
     */
    boolean hasJoin();
    /**
     * <code>.party.Join join = 1;</code>
     * @return The join.
     */
    Party.Join getJoin();

    /**
     * <code>.party.Part part = 2;</code>
     * @return Whether the part field is set.
     */
    boolean hasPart();
    /**
     * <code>.party.Part part = 2;</code>
     * @return The part.
     */
    Party.Part getPart();

    /**
     * <code>.party.Data data = 3;</code>
     * @return Whether the data field is set.
     */
    boolean hasData();
    /**
     * <code>.party.Data data = 3;</code>
     * @return The data.
     */
    Party.Data getData();

    public Party.C2S.MsgCase getMsgCase();
  }
  /**
   * Protobuf type {@code party.C2S}
   */
  public  static final class C2S extends
      com.google.protobuf.GeneratedMessageLite<
          C2S, C2S.Builder> implements
      // @@protoc_insertion_point(message_implements:party.C2S)
      C2SOrBuilder {
    private C2S() {
    }
    private int msgCase_ = 0;
    private java.lang.Object msg_;
    public enum MsgCase {
      JOIN(1),
      PART(2),
      DATA(3),
      MSG_NOT_SET(0);
      private final int value;
      private MsgCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static MsgCase valueOf(int value) {
        return forNumber(value);
      }

      public static MsgCase forNumber(int value) {
        switch (value) {
          case 1: return JOIN;
          case 2: return PART;
          case 3: return DATA;
          case 0: return MSG_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    @java.lang.Override
    public MsgCase
    getMsgCase() {
      return MsgCase.forNumber(
          msgCase_);
    }

    private void clearMsg() {
      msgCase_ = 0;
      msg_ = null;
    }

    public static final int JOIN_FIELD_NUMBER = 1;
    /**
     * <code>.party.Join join = 1;</code>
     */
    @java.lang.Override
    public boolean hasJoin() {
      return msgCase_ == 1;
    }
    /**
     * <code>.party.Join join = 1;</code>
     */
    @java.lang.Override
    public Party.Join getJoin() {
      if (msgCase_ == 1) {
         return (Party.Join) msg_;
      }
      return Party.Join.getDefaultInstance();
    }
    /**
     * <code>.party.Join join = 1;</code>
     */
    private void setJoin(Party.Join value) {
      value.getClass();
  msg_ = value;
      msgCase_ = 1;
    }
    /**
     * <code>.party.Join join = 1;</code>
     */
    private void mergeJoin(Party.Join value) {
      value.getClass();
  if (msgCase_ == 1 &&
          msg_ != Party.Join.getDefaultInstance()) {
        msg_ = Party.Join.newBuilder((Party.Join) msg_)
            .mergeFrom(value).buildPartial();
      } else {
        msg_ = value;
      }
      msgCase_ = 1;
    }
    /**
     * <code>.party.Join join = 1;</code>
     */
    private void clearJoin() {
      if (msgCase_ == 1) {
        msgCase_ = 0;
        msg_ = null;
      }
    }

    public static final int PART_FIELD_NUMBER = 2;
    /**
     * <code>.party.Part part = 2;</code>
     */
    @java.lang.Override
    public boolean hasPart() {
      return msgCase_ == 2;
    }
    /**
     * <code>.party.Part part = 2;</code>
     */
    @java.lang.Override
    public Party.Part getPart() {
      if (msgCase_ == 2) {
         return (Party.Part) msg_;
      }
      return Party.Part.getDefaultInstance();
    }
    /**
     * <code>.party.Part part = 2;</code>
     */
    private void setPart(Party.Part value) {
      value.getClass();
  msg_ = value;
      msgCase_ = 2;
    }
    /**
     * <code>.party.Part part = 2;</code>
     */
    private void mergePart(Party.Part value) {
      value.getClass();
  if (msgCase_ == 2 &&
          msg_ != Party.Part.getDefaultInstance()) {
        msg_ = Party.Part.newBuilder((Party.Part) msg_)
            .mergeFrom(value).buildPartial();
      } else {
        msg_ = value;
      }
      msgCase_ = 2;
    }
    /**
     * <code>.party.Part part = 2;</code>
     */
    private void clearPart() {
      if (msgCase_ == 2) {
        msgCase_ = 0;
        msg_ = null;
      }
    }

    public static final int DATA_FIELD_NUMBER = 3;
    /**
     * <code>.party.Data data = 3;</code>
     */
    @java.lang.Override
    public boolean hasData() {
      return msgCase_ == 3;
    }
    /**
     * <code>.party.Data data = 3;</code>
     */
    @java.lang.Override
    public Party.Data getData() {
      if (msgCase_ == 3) {
         return (Party.Data) msg_;
      }
      return Party.Data.getDefaultInstance();
    }
    /**
     * <code>.party.Data data = 3;</code>
     */
    private void setData(Party.Data value) {
      value.getClass();
  msg_ = value;
      msgCase_ = 3;
    }
    /**
     * <code>.party.Data data = 3;</code>
     */
    private void mergeData(Party.Data value) {
      value.getClass();
  if (msgCase_ == 3 &&
          msg_ != Party.Data.getDefaultInstance()) {
        msg_ = Party.Data.newBuilder((Party.Data) msg_)
            .mergeFrom(value).buildPartial();
      } else {
        msg_ = value;
      }
      msgCase_ = 3;
    }
    /**
     * <code>.party.Data data = 3;</code>
     */
    private void clearData() {
      if (msgCase_ == 3) {
        msgCase_ = 0;
        msg_ = null;
      }
    }

    public static Party.C2S parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Party.C2S parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Party.C2S parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Party.C2S parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Party.C2S parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Party.C2S parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Party.C2S parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Party.C2S parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Party.C2S parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static Party.C2S parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Party.C2S parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Party.C2S parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(Party.C2S prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code party.C2S}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          Party.C2S, Builder> implements
        // @@protoc_insertion_point(builder_implements:party.C2S)
        Party.C2SOrBuilder {
      // Construct using net.runelite.client.party.Party.C2S.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }

      @java.lang.Override
      public MsgCase
          getMsgCase() {
        return instance.getMsgCase();
      }

      public Builder clearMsg() {
        copyOnWrite();
        instance.clearMsg();
        return this;
      }


      /**
       * <code>.party.Join join = 1;</code>
       */
      @java.lang.Override
      public boolean hasJoin() {
        return instance.hasJoin();
      }
      /**
       * <code>.party.Join join = 1;</code>
       */
      @java.lang.Override
      public Party.Join getJoin() {
        return instance.getJoin();
      }
      /**
       * <code>.party.Join join = 1;</code>
       */
      public Builder setJoin(Party.Join value) {
        copyOnWrite();
        instance.setJoin(value);
        return this;
      }
      /**
       * <code>.party.Join join = 1;</code>
       */
      public Builder setJoin(
          Party.Join.Builder builderForValue) {
        copyOnWrite();
        instance.setJoin(builderForValue.build());
        return this;
      }
      /**
       * <code>.party.Join join = 1;</code>
       */
      public Builder mergeJoin(Party.Join value) {
        copyOnWrite();
        instance.mergeJoin(value);
        return this;
      }
      /**
       * <code>.party.Join join = 1;</code>
       */
      public Builder clearJoin() {
        copyOnWrite();
        instance.clearJoin();
        return this;
      }

      /**
       * <code>.party.Part part = 2;</code>
       */
      @java.lang.Override
      public boolean hasPart() {
        return instance.hasPart();
      }
      /**
       * <code>.party.Part part = 2;</code>
       */
      @java.lang.Override
      public Party.Part getPart() {
        return instance.getPart();
      }
      /**
       * <code>.party.Part part = 2;</code>
       */
      public Builder setPart(Party.Part value) {
        copyOnWrite();
        instance.setPart(value);
        return this;
      }
      /**
       * <code>.party.Part part = 2;</code>
       */
      public Builder setPart(
          Party.Part.Builder builderForValue) {
        copyOnWrite();
        instance.setPart(builderForValue.build());
        return this;
      }
      /**
       * <code>.party.Part part = 2;</code>
       */
      public Builder mergePart(Party.Part value) {
        copyOnWrite();
        instance.mergePart(value);
        return this;
      }
      /**
       * <code>.party.Part part = 2;</code>
       */
      public Builder clearPart() {
        copyOnWrite();
        instance.clearPart();
        return this;
      }

      /**
       * <code>.party.Data data = 3;</code>
       */
      @java.lang.Override
      public boolean hasData() {
        return instance.hasData();
      }
      /**
       * <code>.party.Data data = 3;</code>
       */
      @java.lang.Override
      public Party.Data getData() {
        return instance.getData();
      }
      /**
       * <code>.party.Data data = 3;</code>
       */
      public Builder setData(Party.Data value) {
        copyOnWrite();
        instance.setData(value);
        return this;
      }
      /**
       * <code>.party.Data data = 3;</code>
       */
      public Builder setData(
          Party.Data.Builder builderForValue) {
        copyOnWrite();
        instance.setData(builderForValue.build());
        return this;
      }
      /**
       * <code>.party.Data data = 3;</code>
       */
      public Builder mergeData(Party.Data value) {
        copyOnWrite();
        instance.mergeData(value);
        return this;
      }
      /**
       * <code>.party.Data data = 3;</code>
       */
      public Builder clearData() {
        copyOnWrite();
        instance.clearData();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:party.C2S)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new Party.C2S();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "msg_",
              "msgCase_",
              Party.Join.class,
              Party.Part.class,
              Party.Data.class,
            };
            java.lang.String info =
                "\u0000\u0003\u0001\u0000\u0001\u0003\u0003\u0000\u0000\u0000\u0001<\u0000\u0002<" +
                "\u0000\u0003<\u0000";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<Party.C2S> parser = PARSER;
          if (parser == null) {
            synchronized (Party.C2S.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<Party.C2S>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:party.C2S)
    private static final Party.C2S DEFAULT_INSTANCE;
    static {
      C2S defaultInstance = new C2S();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        C2S.class, defaultInstance);
    }

    public static Party.C2S getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<C2S> PARSER;

    public static com.google.protobuf.Parser<C2S> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface UserJoinOrBuilder extends
      // @@protoc_insertion_point(interface_extends:party.UserJoin)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>int64 partyId = 1;</code>
     * @return The partyId.
     */
    long getPartyId();

    /**
     * <code>int64 memberId = 2;</code>
     * @return The memberId.
     */
    long getMemberId();
  }
  /**
   * <pre>
   * s-&gt;c
   * </pre>
   *
   * Protobuf type {@code party.UserJoin}
   */
  public  static final class UserJoin extends
      com.google.protobuf.GeneratedMessageLite<
          UserJoin, UserJoin.Builder> implements
      // @@protoc_insertion_point(message_implements:party.UserJoin)
      UserJoinOrBuilder {
    private UserJoin() {
    }
    public static final int PARTYID_FIELD_NUMBER = 1;
    private long partyId_;
    /**
     * <code>int64 partyId = 1;</code>
     * @return The partyId.
     */
    @java.lang.Override
    public long getPartyId() {
      return partyId_;
    }
    /**
     * <code>int64 partyId = 1;</code>
     * @param value The partyId to set.
     */
    private void setPartyId(long value) {
      
      partyId_ = value;
    }
    /**
     * <code>int64 partyId = 1;</code>
     */
    private void clearPartyId() {
      
      partyId_ = 0L;
    }

    public static final int MEMBERID_FIELD_NUMBER = 2;
    private long memberId_;
    /**
     * <code>int64 memberId = 2;</code>
     * @return The memberId.
     */
    @java.lang.Override
    public long getMemberId() {
      return memberId_;
    }
    /**
     * <code>int64 memberId = 2;</code>
     * @param value The memberId to set.
     */
    private void setMemberId(long value) {
      
      memberId_ = value;
    }
    /**
     * <code>int64 memberId = 2;</code>
     */
    private void clearMemberId() {
      
      memberId_ = 0L;
    }

    public static Party.UserJoin parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Party.UserJoin parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Party.UserJoin parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Party.UserJoin parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Party.UserJoin parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Party.UserJoin parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Party.UserJoin parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Party.UserJoin parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Party.UserJoin parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static Party.UserJoin parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Party.UserJoin parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Party.UserJoin parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(Party.UserJoin prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * s-&gt;c
     * </pre>
     *
     * Protobuf type {@code party.UserJoin}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          Party.UserJoin, Builder> implements
        // @@protoc_insertion_point(builder_implements:party.UserJoin)
        Party.UserJoinOrBuilder {
      // Construct using net.runelite.client.party.Party.UserJoin.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>int64 partyId = 1;</code>
       * @return The partyId.
       */
      @java.lang.Override
      public long getPartyId() {
        return instance.getPartyId();
      }
      /**
       * <code>int64 partyId = 1;</code>
       * @param value The partyId to set.
       * @return This builder for chaining.
       */
      public Builder setPartyId(long value) {
        copyOnWrite();
        instance.setPartyId(value);
        return this;
      }
      /**
       * <code>int64 partyId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPartyId() {
        copyOnWrite();
        instance.clearPartyId();
        return this;
      }

      /**
       * <code>int64 memberId = 2;</code>
       * @return The memberId.
       */
      @java.lang.Override
      public long getMemberId() {
        return instance.getMemberId();
      }
      /**
       * <code>int64 memberId = 2;</code>
       * @param value The memberId to set.
       * @return This builder for chaining.
       */
      public Builder setMemberId(long value) {
        copyOnWrite();
        instance.setMemberId(value);
        return this;
      }
      /**
       * <code>int64 memberId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMemberId() {
        copyOnWrite();
        instance.clearMemberId();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:party.UserJoin)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new Party.UserJoin();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "partyId_",
              "memberId_",
            };
            java.lang.String info =
                "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0002\u0002\u0002" +
                "";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<Party.UserJoin> parser = PARSER;
          if (parser == null) {
            synchronized (Party.UserJoin.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<Party.UserJoin>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:party.UserJoin)
    private static final Party.UserJoin DEFAULT_INSTANCE;
    static {
      UserJoin defaultInstance = new UserJoin();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        UserJoin.class, defaultInstance);
    }

    public static Party.UserJoin getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<UserJoin> PARSER;

    public static com.google.protobuf.Parser<UserJoin> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface UserPartOrBuilder extends
      // @@protoc_insertion_point(interface_extends:party.UserPart)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>int64 partyId = 1;</code>
     * @return The partyId.
     */
    long getPartyId();

    /**
     * <code>int64 memberId = 2;</code>
     * @return The memberId.
     */
    long getMemberId();
  }
  /**
   * Protobuf type {@code party.UserPart}
   */
  public  static final class UserPart extends
      com.google.protobuf.GeneratedMessageLite<
          UserPart, UserPart.Builder> implements
      // @@protoc_insertion_point(message_implements:party.UserPart)
      UserPartOrBuilder {
    private UserPart() {
    }
    public static final int PARTYID_FIELD_NUMBER = 1;
    private long partyId_;
    /**
     * <code>int64 partyId = 1;</code>
     * @return The partyId.
     */
    @java.lang.Override
    public long getPartyId() {
      return partyId_;
    }
    /**
     * <code>int64 partyId = 1;</code>
     * @param value The partyId to set.
     */
    private void setPartyId(long value) {
      
      partyId_ = value;
    }
    /**
     * <code>int64 partyId = 1;</code>
     */
    private void clearPartyId() {
      
      partyId_ = 0L;
    }

    public static final int MEMBERID_FIELD_NUMBER = 2;
    private long memberId_;
    /**
     * <code>int64 memberId = 2;</code>
     * @return The memberId.
     */
    @java.lang.Override
    public long getMemberId() {
      return memberId_;
    }
    /**
     * <code>int64 memberId = 2;</code>
     * @param value The memberId to set.
     */
    private void setMemberId(long value) {
      
      memberId_ = value;
    }
    /**
     * <code>int64 memberId = 2;</code>
     */
    private void clearMemberId() {
      
      memberId_ = 0L;
    }

    public static Party.UserPart parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Party.UserPart parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Party.UserPart parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Party.UserPart parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Party.UserPart parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Party.UserPart parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Party.UserPart parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Party.UserPart parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Party.UserPart parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static Party.UserPart parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Party.UserPart parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Party.UserPart parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(Party.UserPart prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code party.UserPart}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          Party.UserPart, Builder> implements
        // @@protoc_insertion_point(builder_implements:party.UserPart)
        Party.UserPartOrBuilder {
      // Construct using net.runelite.client.party.Party.UserPart.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>int64 partyId = 1;</code>
       * @return The partyId.
       */
      @java.lang.Override
      public long getPartyId() {
        return instance.getPartyId();
      }
      /**
       * <code>int64 partyId = 1;</code>
       * @param value The partyId to set.
       * @return This builder for chaining.
       */
      public Builder setPartyId(long value) {
        copyOnWrite();
        instance.setPartyId(value);
        return this;
      }
      /**
       * <code>int64 partyId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPartyId() {
        copyOnWrite();
        instance.clearPartyId();
        return this;
      }

      /**
       * <code>int64 memberId = 2;</code>
       * @return The memberId.
       */
      @java.lang.Override
      public long getMemberId() {
        return instance.getMemberId();
      }
      /**
       * <code>int64 memberId = 2;</code>
       * @param value The memberId to set.
       * @return This builder for chaining.
       */
      public Builder setMemberId(long value) {
        copyOnWrite();
        instance.setMemberId(value);
        return this;
      }
      /**
       * <code>int64 memberId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMemberId() {
        copyOnWrite();
        instance.clearMemberId();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:party.UserPart)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new Party.UserPart();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "partyId_",
              "memberId_",
            };
            java.lang.String info =
                "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0002\u0002\u0002" +
                "";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<Party.UserPart> parser = PARSER;
          if (parser == null) {
            synchronized (Party.UserPart.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<Party.UserPart>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:party.UserPart)
    private static final Party.UserPart DEFAULT_INSTANCE;
    static {
      UserPart defaultInstance = new UserPart();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        UserPart.class, defaultInstance);
    }

    public static Party.UserPart getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<UserPart> PARSER;

    public static com.google.protobuf.Parser<UserPart> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface PartyDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:party.PartyData)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>int64 partyId = 1;</code>
     * @return The partyId.
     */
    long getPartyId();

    /**
     * <code>int64 memberId = 2;</code>
     * @return The memberId.
     */
    long getMemberId();

    /**
     * <code>bytes data = 3;</code>
     * @return The data.
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code party.PartyData}
   */
  public  static final class PartyData extends
      com.google.protobuf.GeneratedMessageLite<
          PartyData, PartyData.Builder> implements
      // @@protoc_insertion_point(message_implements:party.PartyData)
      PartyDataOrBuilder {
    private PartyData() {
      data_ = com.google.protobuf.ByteString.EMPTY;
    }
    public static final int PARTYID_FIELD_NUMBER = 1;
    private long partyId_;
    /**
     * <code>int64 partyId = 1;</code>
     * @return The partyId.
     */
    @java.lang.Override
    public long getPartyId() {
      return partyId_;
    }
    /**
     * <code>int64 partyId = 1;</code>
     * @param value The partyId to set.
     */
    private void setPartyId(long value) {
      
      partyId_ = value;
    }
    /**
     * <code>int64 partyId = 1;</code>
     */
    private void clearPartyId() {
      
      partyId_ = 0L;
    }

    public static final int MEMBERID_FIELD_NUMBER = 2;
    private long memberId_;
    /**
     * <code>int64 memberId = 2;</code>
     * @return The memberId.
     */
    @java.lang.Override
    public long getMemberId() {
      return memberId_;
    }
    /**
     * <code>int64 memberId = 2;</code>
     * @param value The memberId to set.
     */
    private void setMemberId(long value) {
      
      memberId_ = value;
    }
    /**
     * <code>int64 memberId = 2;</code>
     */
    private void clearMemberId() {
      
      memberId_ = 0L;
    }

    public static final int DATA_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>bytes data = 3;</code>
     * @return The data.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getData() {
      return data_;
    }
    /**
     * <code>bytes data = 3;</code>
     * @param value The data to set.
     */
    private void setData(com.google.protobuf.ByteString value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      data_ = value;
    }
    /**
     * <code>bytes data = 3;</code>
     */
    private void clearData() {
      
      data_ = getDefaultInstance().getData();
    }

    public static Party.PartyData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Party.PartyData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Party.PartyData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Party.PartyData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Party.PartyData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Party.PartyData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Party.PartyData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Party.PartyData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Party.PartyData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static Party.PartyData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Party.PartyData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Party.PartyData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(Party.PartyData prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code party.PartyData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          Party.PartyData, Builder> implements
        // @@protoc_insertion_point(builder_implements:party.PartyData)
        Party.PartyDataOrBuilder {
      // Construct using net.runelite.client.party.Party.PartyData.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>int64 partyId = 1;</code>
       * @return The partyId.
       */
      @java.lang.Override
      public long getPartyId() {
        return instance.getPartyId();
      }
      /**
       * <code>int64 partyId = 1;</code>
       * @param value The partyId to set.
       * @return This builder for chaining.
       */
      public Builder setPartyId(long value) {
        copyOnWrite();
        instance.setPartyId(value);
        return this;
      }
      /**
       * <code>int64 partyId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPartyId() {
        copyOnWrite();
        instance.clearPartyId();
        return this;
      }

      /**
       * <code>int64 memberId = 2;</code>
       * @return The memberId.
       */
      @java.lang.Override
      public long getMemberId() {
        return instance.getMemberId();
      }
      /**
       * <code>int64 memberId = 2;</code>
       * @param value The memberId to set.
       * @return This builder for chaining.
       */
      public Builder setMemberId(long value) {
        copyOnWrite();
        instance.setMemberId(value);
        return this;
      }
      /**
       * <code>int64 memberId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMemberId() {
        copyOnWrite();
        instance.clearMemberId();
        return this;
      }

      /**
       * <code>bytes data = 3;</code>
       * @return The data.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getData() {
        return instance.getData();
      }
      /**
       * <code>bytes data = 3;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setData(value);
        return this;
      }
      /**
       * <code>bytes data = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        copyOnWrite();
        instance.clearData();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:party.PartyData)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new Party.PartyData();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "partyId_",
              "memberId_",
              "data_",
            };
            java.lang.String info =
                "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u0002\u0002\u0002" +
                "\u0003\n";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<Party.PartyData> parser = PARSER;
          if (parser == null) {
            synchronized (Party.PartyData.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<Party.PartyData>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:party.PartyData)
    private static final Party.PartyData DEFAULT_INSTANCE;
    static {
      PartyData defaultInstance = new PartyData();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        PartyData.class, defaultInstance);
    }

    public static Party.PartyData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<PartyData> PARSER;

    public static com.google.protobuf.Parser<PartyData> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface S2COrBuilder extends
      // @@protoc_insertion_point(interface_extends:party.S2C)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>.party.UserJoin join = 1;</code>
     * @return Whether the join field is set.
     */
    boolean hasJoin();
    /**
     * <code>.party.UserJoin join = 1;</code>
     * @return The join.
     */
    Party.UserJoin getJoin();

    /**
     * <code>.party.UserPart part = 2;</code>
     * @return Whether the part field is set.
     */
    boolean hasPart();
    /**
     * <code>.party.UserPart part = 2;</code>
     * @return The part.
     */
    Party.UserPart getPart();

    /**
     * <code>.party.PartyData data = 3;</code>
     * @return Whether the data field is set.
     */
    boolean hasData();
    /**
     * <code>.party.PartyData data = 3;</code>
     * @return The data.
     */
    Party.PartyData getData();

    public Party.S2C.MsgCase getMsgCase();
  }
  /**
   * Protobuf type {@code party.S2C}
   */
  public  static final class S2C extends
      com.google.protobuf.GeneratedMessageLite<
          S2C, S2C.Builder> implements
      // @@protoc_insertion_point(message_implements:party.S2C)
      S2COrBuilder {
    private S2C() {
    }
    private int msgCase_ = 0;
    private java.lang.Object msg_;
    public enum MsgCase {
      JOIN(1),
      PART(2),
      DATA(3),
      MSG_NOT_SET(0);
      private final int value;
      private MsgCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static MsgCase valueOf(int value) {
        return forNumber(value);
      }

      public static MsgCase forNumber(int value) {
        switch (value) {
          case 1: return JOIN;
          case 2: return PART;
          case 3: return DATA;
          case 0: return MSG_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    @java.lang.Override
    public MsgCase
    getMsgCase() {
      return MsgCase.forNumber(
          msgCase_);
    }

    private void clearMsg() {
      msgCase_ = 0;
      msg_ = null;
    }

    public static final int JOIN_FIELD_NUMBER = 1;
    /**
     * <code>.party.UserJoin join = 1;</code>
     */
    @java.lang.Override
    public boolean hasJoin() {
      return msgCase_ == 1;
    }
    /**
     * <code>.party.UserJoin join = 1;</code>
     */
    @java.lang.Override
    public Party.UserJoin getJoin() {
      if (msgCase_ == 1) {
         return (Party.UserJoin) msg_;
      }
      return Party.UserJoin.getDefaultInstance();
    }
    /**
     * <code>.party.UserJoin join = 1;</code>
     */
    private void setJoin(Party.UserJoin value) {
      value.getClass();
  msg_ = value;
      msgCase_ = 1;
    }
    /**
     * <code>.party.UserJoin join = 1;</code>
     */
    private void mergeJoin(Party.UserJoin value) {
      value.getClass();
  if (msgCase_ == 1 &&
          msg_ != Party.UserJoin.getDefaultInstance()) {
        msg_ = Party.UserJoin.newBuilder((Party.UserJoin) msg_)
            .mergeFrom(value).buildPartial();
      } else {
        msg_ = value;
      }
      msgCase_ = 1;
    }
    /**
     * <code>.party.UserJoin join = 1;</code>
     */
    private void clearJoin() {
      if (msgCase_ == 1) {
        msgCase_ = 0;
        msg_ = null;
      }
    }

    public static final int PART_FIELD_NUMBER = 2;
    /**
     * <code>.party.UserPart part = 2;</code>
     */
    @java.lang.Override
    public boolean hasPart() {
      return msgCase_ == 2;
    }
    /**
     * <code>.party.UserPart part = 2;</code>
     */
    @java.lang.Override
    public Party.UserPart getPart() {
      if (msgCase_ == 2) {
         return (Party.UserPart) msg_;
      }
      return Party.UserPart.getDefaultInstance();
    }
    /**
     * <code>.party.UserPart part = 2;</code>
     */
    private void setPart(Party.UserPart value) {
      value.getClass();
  msg_ = value;
      msgCase_ = 2;
    }
    /**
     * <code>.party.UserPart part = 2;</code>
     */
    private void mergePart(Party.UserPart value) {
      value.getClass();
  if (msgCase_ == 2 &&
          msg_ != Party.UserPart.getDefaultInstance()) {
        msg_ = Party.UserPart.newBuilder((Party.UserPart) msg_)
            .mergeFrom(value).buildPartial();
      } else {
        msg_ = value;
      }
      msgCase_ = 2;
    }
    /**
     * <code>.party.UserPart part = 2;</code>
     */
    private void clearPart() {
      if (msgCase_ == 2) {
        msgCase_ = 0;
        msg_ = null;
      }
    }

    public static final int DATA_FIELD_NUMBER = 3;
    /**
     * <code>.party.PartyData data = 3;</code>
     */
    @java.lang.Override
    public boolean hasData() {
      return msgCase_ == 3;
    }
    /**
     * <code>.party.PartyData data = 3;</code>
     */
    @java.lang.Override
    public Party.PartyData getData() {
      if (msgCase_ == 3) {
         return (Party.PartyData) msg_;
      }
      return Party.PartyData.getDefaultInstance();
    }
    /**
     * <code>.party.PartyData data = 3;</code>
     */
    private void setData(Party.PartyData value) {
      value.getClass();
  msg_ = value;
      msgCase_ = 3;
    }
    /**
     * <code>.party.PartyData data = 3;</code>
     */
    private void mergeData(Party.PartyData value) {
      value.getClass();
  if (msgCase_ == 3 &&
          msg_ != Party.PartyData.getDefaultInstance()) {
        msg_ = Party.PartyData.newBuilder((Party.PartyData) msg_)
            .mergeFrom(value).buildPartial();
      } else {
        msg_ = value;
      }
      msgCase_ = 3;
    }
    /**
     * <code>.party.PartyData data = 3;</code>
     */
    private void clearData() {
      if (msgCase_ == 3) {
        msgCase_ = 0;
        msg_ = null;
      }
    }

    public static Party.S2C parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Party.S2C parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Party.S2C parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Party.S2C parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Party.S2C parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Party.S2C parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Party.S2C parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Party.S2C parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Party.S2C parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static Party.S2C parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Party.S2C parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Party.S2C parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(Party.S2C prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code party.S2C}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          Party.S2C, Builder> implements
        // @@protoc_insertion_point(builder_implements:party.S2C)
        Party.S2COrBuilder {
      // Construct using net.runelite.client.party.Party.S2C.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }

      @java.lang.Override
      public MsgCase
          getMsgCase() {
        return instance.getMsgCase();
      }

      public Builder clearMsg() {
        copyOnWrite();
        instance.clearMsg();
        return this;
      }


      /**
       * <code>.party.UserJoin join = 1;</code>
       */
      @java.lang.Override
      public boolean hasJoin() {
        return instance.hasJoin();
      }
      /**
       * <code>.party.UserJoin join = 1;</code>
       */
      @java.lang.Override
      public Party.UserJoin getJoin() {
        return instance.getJoin();
      }
      /**
       * <code>.party.UserJoin join = 1;</code>
       */
      public Builder setJoin(Party.UserJoin value) {
        copyOnWrite();
        instance.setJoin(value);
        return this;
      }
      /**
       * <code>.party.UserJoin join = 1;</code>
       */
      public Builder setJoin(
          Party.UserJoin.Builder builderForValue) {
        copyOnWrite();
        instance.setJoin(builderForValue.build());
        return this;
      }
      /**
       * <code>.party.UserJoin join = 1;</code>
       */
      public Builder mergeJoin(Party.UserJoin value) {
        copyOnWrite();
        instance.mergeJoin(value);
        return this;
      }
      /**
       * <code>.party.UserJoin join = 1;</code>
       */
      public Builder clearJoin() {
        copyOnWrite();
        instance.clearJoin();
        return this;
      }

      /**
       * <code>.party.UserPart part = 2;</code>
       */
      @java.lang.Override
      public boolean hasPart() {
        return instance.hasPart();
      }
      /**
       * <code>.party.UserPart part = 2;</code>
       */
      @java.lang.Override
      public Party.UserPart getPart() {
        return instance.getPart();
      }
      /**
       * <code>.party.UserPart part = 2;</code>
       */
      public Builder setPart(Party.UserPart value) {
        copyOnWrite();
        instance.setPart(value);
        return this;
      }
      /**
       * <code>.party.UserPart part = 2;</code>
       */
      public Builder setPart(
          Party.UserPart.Builder builderForValue) {
        copyOnWrite();
        instance.setPart(builderForValue.build());
        return this;
      }
      /**
       * <code>.party.UserPart part = 2;</code>
       */
      public Builder mergePart(Party.UserPart value) {
        copyOnWrite();
        instance.mergePart(value);
        return this;
      }
      /**
       * <code>.party.UserPart part = 2;</code>
       */
      public Builder clearPart() {
        copyOnWrite();
        instance.clearPart();
        return this;
      }

      /**
       * <code>.party.PartyData data = 3;</code>
       */
      @java.lang.Override
      public boolean hasData() {
        return instance.hasData();
      }
      /**
       * <code>.party.PartyData data = 3;</code>
       */
      @java.lang.Override
      public Party.PartyData getData() {
        return instance.getData();
      }
      /**
       * <code>.party.PartyData data = 3;</code>
       */
      public Builder setData(Party.PartyData value) {
        copyOnWrite();
        instance.setData(value);
        return this;
      }
      /**
       * <code>.party.PartyData data = 3;</code>
       */
      public Builder setData(
          Party.PartyData.Builder builderForValue) {
        copyOnWrite();
        instance.setData(builderForValue.build());
        return this;
      }
      /**
       * <code>.party.PartyData data = 3;</code>
       */
      public Builder mergeData(Party.PartyData value) {
        copyOnWrite();
        instance.mergeData(value);
        return this;
      }
      /**
       * <code>.party.PartyData data = 3;</code>
       */
      public Builder clearData() {
        copyOnWrite();
        instance.clearData();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:party.S2C)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new Party.S2C();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "msg_",
              "msgCase_",
              Party.UserJoin.class,
              Party.UserPart.class,
              Party.PartyData.class,
            };
            java.lang.String info =
                "\u0000\u0003\u0001\u0000\u0001\u0003\u0003\u0000\u0000\u0000\u0001<\u0000\u0002<" +
                "\u0000\u0003<\u0000";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<Party.S2C> parser = PARSER;
          if (parser == null) {
            synchronized (Party.S2C.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<Party.S2C>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:party.S2C)
    private static final Party.S2C DEFAULT_INSTANCE;
    static {
      S2C defaultInstance = new S2C();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        S2C.class, defaultInstance);
    }

    public static Party.S2C getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<S2C> PARSER;

    public static com.google.protobuf.Parser<S2C> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
